### PR TITLE
More fixes

### PR DESCRIPTION
**Pull request by alexdowad**

### CODE REVIEW

**Comment by alexdowad** [comment]
Dear @ericmg,

I have finished reading the Using-D3.js book. It was very helpful; thank you! Most of the remaining spelling, grammar, etc. fixes which I found are in this PR. (There are a couple more which I haven't pushed yet.)

Question. Would you accept a contribution of a new chapter? And if so, the next question would be... what should it be about? I like this book enough that I would be happy to do some more work on it.

**Comment by Legion4444** [comment]
Hi @alexdowad. I am not your intended respondent, but I helped write/edit a lot of the shapes and events chapters and may be able to answer this one. First of all, thank you for all your edits on the book! I have been following your edits since you started and I really appreciate it. I am sure @erimcg will accept this pull request when he gets a chance. 

I can't imagine there would be any real pushbacks to you contributing to the book given its open sourcey nature. If you were wanting ideas on where to start, we did have a [roadmap](http://using-d3js.com/using_d3js_roadmap.html) for things we wanted to add. Some of the roadmap may have already been completed like Dispatches and Timers, but most haven't been put in. 

If I would've added another chapter while I was working on it, it would've likely been an "Interactive Visualizations" chapter. I think [d3-drag](https://github.com/d3/d3-drag), [d3-zoom](https://github.com/d3/d3-zoom), and [d3-transition](https://github.com/d3/d3-transition]) (which may use [d3-ease](https://github.com/d3/d3-ease) IIRC) would be good additions to such a chapter. 

If that doesn't float your boat, from the roadmap we also have: various Utilities that likely would go into Scales and Axis or maybe a new chapter; Interpolators which seems to fit with the scales in Scales and Axis also; Layouts that would go into the Hierarchal Layouts or Other Layouts; and Data Structures (which I'm not exactly sure where they would go).

Again, thank you for all the work you have done thus far.

**Comment by alexdowad** [comment]
Dear @Legion4444, thanks very much for the response. I am just researching d3-transition (mostly just reading the source) and would like to try writing something about it.

As with the rest of the D3 "family", d3-transition is a tiny little jewel. It's less than 800 lines of JS; mainly just a wrapper around d3-timer, d3-ease, d3-interpolate, and d3-select which puts them together to give you transitions.

**Comment by erimcg** [comment]
Hi @alexdowad, Thanks for the corrections!  I've merged them and will update the site shortly.  Also, sincere thanks you for your offer to add additional chapters... let's discuss via email.

**Comment by erimcg** [comment]
Added editorial changes from @alexdowad.

**Comment by alexdowad** [comment]
> Hi @alexdowad, Thanks for the corrections! I've merged them and will update the site shortly. Also, sincere thanks you for your offer to add additional chapters... let's discuss via email.

Sounds good! Do you have my e-mail address?

**Pull request merged**
